
FLAGS = -Wall -pthread -I../include

all:
	gcc $(FLAGS) -o dining_philosophers_deadlock dining_philosophers_deadlock.c 
	gcc $(FLAGS) -o dining_philosophers_deadlock_print dining_philosophers_deadlock_print.c 
	gcc $(FLAGS) -o dining_philosophers_no_deadlock dining_philosophers_no_deadlock.c 
	gcc $(FLAGS) -o dining_philosophers_no_deadlock_print dining_philosophers_no_deadlock_print.c

